name: Run Event Bot

on:
  schedule:
    - cron: "0 13 * * *"  # 毎日0時(JST9時)に実行
  workflow_dispatch:      # 手動実行も可能

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 gspread google-auth

      - name: Run event bot
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python event_bot.py

